#! bin/zsh

# Programs
alias c="code -r ."
alias f="fzf"
alias v="vim ."
alias g="git"
alias gr="grep"
alias t="tmux"

# Python
alias py="python3.7"
alias pip="pip3.7"
alias dr="python3.7 manage.py runserver"
alias dt="python3.7 manage.py test"
alias dmm="python3.7 manage.py makemigrations"
alias dm="python3.7 manage.py migrate"
alias dsh="python3.7 manage.py shell"
alias dsa="python3.7 manage.py startapp"
alias dcs="python3.7 manage.py collectstatic"

# Util
alias wo="cd ~ && cd Documents/workspace"
alias dot="cd ~ && cd Documents/workspace/dotfiles"
alias pymod="touch __init__.py"
alias mongoon="service mongod start"
alias mongooff="service mongod stop"
alias gitignore="cp -f ~/.gitignore ./.gitignore"
alias http="http --style lovelace"
alias ex="exec zsh"

# Javascript
alias nm="nodemon"
alias npms="npm start"
alias npmt="npm test"