#! bin/zsh

alias nm="nodemon"
alias npms="npm start"
alias npmt="npm test"
alias py="python3.7"
alias pip="pip3.7"
alias ex="exec zsh"
alias v="vim ."
alias g="git"
alias gr="grep"
alias t="tmux"
alias tag="ctags -R ."
