#!/bin/zsh

# Programs
alias c="code -r ."
alias f="fzf"
alias v="nvim ."
alias vi="nvim"
alias g="git"
alias t="tmux"
alias l="ls -la --group-directories-first"

# Tmuxp sessions
alias tdot="tmuxp load dot"

# Python
alias python="python3"
alias pip="python3 -m pip"
alias dr="./manage.py runserver"
alias dt="./manage.py test"
alias dmm="./manage.py makemigrations"
alias dm="./manage.py migrate"
alias dsh="./manage.py shell"
alias dsa="./manage.py startapp"
alias dcs="./manage.py collectstatic"

# Util
if [ $theme_color = 'light' ]; then
  alias http="http --style xcode"
else
  alias http="http --style lovelace"
fi

alias wo="cd ~ && cd Documents/workspace"
alias dot="cd ~ && cd Documents/workspace/dotfiles"
alias pymod="touch __init__.py"
alias mongoon="service mongod start"
alias mongooff="service mongod stop"
alias gitignore="cp -f ~/.gitignore ./.gitignore"
alias ex="exec zsh"
alias cl="clear"

# Javascript
alias nm="nodemon"
alias npms="npm start"
alias npmt="npm test"

# Documentation mirrors
alias docpython="google-chrome --new-window ~/Documents/workspace/Docs/docs.python.org/3/index.html"
alias docdjango="google-chrome --new-window ~/Documents/workspace/Docs/docs.djangoproject.com/en/3.0/index.html"