#!/bin/zsh

export ZSH=/home/dim/.oh-my-zsh
export PATH=$HOME/bin:$HOME/.local/bin:$PATH;
export EDITOR="vim"

# FZF config
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Ag config
if type ag &> /dev/null; then
  export FZF_DEFAULT_COMMAND='ag -p ~/.gitignore --hidden -g ""'
fi

ZSH_THEME="dnonov"

plugins=(
  vi-mode
  gulp
  heroku
  httpie
  ubuntu
  vundle
  virtualenv
)
source $ZSH/oh-my-zsh.sh

# Predicates vim, tmux and fzf color scheme
export theme_color="light"

# Prevents inactive vim on Ctrl-s
stty -ixon
