#! /bin/zsh

export ZSH=/home/dim/.oh-my-zsh
export PATH=$HOME/bin:$PATH;
export EDITOR="vim"

# FZF config
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

ZSH_THEME="dnonov"

# Bullet-train theme setting
BULLETTRAIN_PROMPT_CHAR=" "
BULLETTRAIN_GIT_BG=black
BULLETTRAIN_GIT_FG=white

BULLETTRAIN_PROMPT_ORDER=(
	status
	custom
	dir
	screen
	virtualenv
	aws
	git
	hg
	cmd_exec_time
)
plugins=(
  vi-mode,
  gulp,
  heroku,
  httpie,
  ubuntu,
  vundle,
  virtualenv
)
source $ZSH/oh-my-zsh.sh

# Prevents inactive vim on Ctrl-s
stty -ixon
