#! /bin/zsh

function mktouch() {
  mkdir -p $(dirname $1) && touch $1;
}

function fh() {
  eval $( ([ -n "$ZSH_NAME" ] && fc -l 1 || history) | fzf +s --tac | sed 's/ *[0-9]* *//')
}

function search_easy() {
  # Exclude regex defaults to 'node_modules'
  exclude_regex=${2:-'*/node_modules/*'};
  file_name_regex=$1;

  find . -path "${exclude_regex}" -prune -o -iname "${file_name_regex}" -print;
}