#!/bin/zsh

function mktouch() {
  mkdir -p $(dirname $1) && touch $1;
}

function fh() {
  eval $( ([ -n "$ZSH_NAME" ] && fc -l 1 || history) | fzf +s --tac | sed 's/ *[0-9]* *//')
}

function search_easy() {
  # Exclude regex defaults to 'node_modules'
  exclude_regex=${2:-'*/node_modules/*'};
  file_name_regex=$1;

  find . -path "${exclude_regex}" -prune -o -iname "${file_name_regex}" -print;
}

function mirror() {
  if [ $# -eq 0 ]; then
    echo "Need a URL"
  else
    wget -mkEpnp $1
  fi
}
function _cloc() {
  exclude_dirs=${1:-'node_modules'};

  cloc --exclude-dir="${exclude_dirs}" .
}
