#!/bin/zsh

function mktouch() {
  mkdir -p $(dirname $1) && touch $1;
}

function mkfilevim() {
  touch $1 && nvim $1
}

function fh() {
  eval $( ([ -n "$ZSH_NAME" ] && fc -l 1 || history) | fzf +s --tac | sed 's/ *[0-9]* *//')
}

function search_easy() {
  # Exclude regex defaults to 'node_modules'
  exclude_regex=${2:-'*/node_modules/*'};
  file_name_regex=$1;

  find . -path "${exclude_regex}" -prune -o -iname "${file_name_regex}" -print;
}

function mirror() {
  if [ $# -eq 0 ]; then
    echo "Need a URL"
  else
    wget -mkEpnp $1
  fi
}

function show256() {
  for i in {0..255} ; do
    printf "\x1b[48;5;%sm%3d\e[0m " "$i" "$i"
    if (( i == 15 )) || (( i > 15 )) && (( (i-15) % 6 == 0 )); then
        printf "\n";
    fi
  done
}

function _cloc() {
  exclude_dirs=${1:-'node_modules'};

  cloc --exclude-dir="${exclude_dirs}" .
}

function ports() {
  watch -n 1 "sudo lsof -i"
}

function ..() {
  if [ $# -lt 1 ]; then
    cd ..
  else
    local re='^[0-9]+$'
    if [[ "$1" =~ $re ]]; then
      for i in $(seq $1); do
        cd ..
      done
    else
      cd ..
    fi
  fi
}